name: Check code codestyle with Prettier

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm
          cache-dependeny-path: pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm i
      - name: Run prettier
        run: pnpm run prettier
